AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
